### ISSUE TITLE
Upgrade to latest qbitorrent version

### ISSUE THREAD

**Issue by jhjm32087** [wernight/docker-qbittorrent#11]
Any clue when the next version of qbitorrent is going to be updated?

**Comment by wernight** [comment]
3.3.3 is tagged, 3.3.12 (latest released) isn't tagger but should be `:latest`. Which version exactly are you missing?

**Comment by wernight** [comment]
Ha! I see `:latest` didn't build.

**Comment by wernight** [comment]
Fixed ! I think the latest source code snapshot will again give issues once it's released but for now it's compiling.
