### ISSUE TITLE
Remote WebUI Access is broken in qbittorrent 3.3.13

### ISSUE THREAD

**Issue by rflagler** [wernight/docker-qbittorrent#12]
The latest docker image of qbittorrent you have uses 3.3.13 which doesn't allow any UI except the provided one. Can you update the image to v3.3.14 which has the fix?

**Comment by wernight** [comment]
The API is 3.3.13 requires to pass extra headers which is a pain. Should be upgraded now or building

**Comment by rflagler** [comment]
Thanks, your latest image resolves this issue.
