### ISSUE TITLE
Feature Request - Add unrar to the docker image

### ISSUE THREAD

**Issue by rflagler** [wernight/docker-qbittorrent#13]
The docker image doesn't include unrar so we can't utilize the "run external program on torrent completion" to auto-extract compressed torrents. Could it be included?

**Comment by wernight** [comment]
You can use but different people want to do different things upon completion, including myself. What I do is a Dockerfile like:

    FROM wernight/qbittorrent
    RUN apk add --no-cache unrar

I forgot if you need a `USER` command before.

**Comment by rflagler** [comment]
Very cool, I wasn't aware I could build an image based on yours. Thanks for the information.
