### ISSUE TITLE
change webgui port

### ISSUE THREAD

**Issue by fadern** [wernight/docker-qbittorrent#16]
Hi,

The webgui isnt reachable when its using port 8080 I need to change it. Not just redirecting the port.
ive tried to redirect but qbit doesn't like it...

(W) 2018-01-22T20:45:50 - WebUI: Invalid Host header, port mismatch.
Request source IP: '::ffff:172.17.0.1'. Server port: '8080'. Received Host header: '192.168.1.51:8112'

(port 8080 is used by another application)

**Comment by wernight** [comment]
netstat check what is using that port.

**Comment by fadern** [comment]
i know what is using that port. its a unifi controller. is it possible to change the webui port that qbit are using?

**Comment by wernight** [comment]
See use `docker run -p`.
