### ISSUE TITLE
Search engine option not there

### ISSUE THREAD

**Issue by janastasiou** [wernight/docker-qbittorrent#18]
I've notice that the full client of qbittorrent has a search engine built in.

Does this docker version  of qbittorent have this available as well?

**Comment by wernight** [comment]
Only the GUI client has that. Their web UI never had it so far.

**Comment by lor-enz** [comment]
Search has been added to the webui in the release from Dec 24 2018
https://github.com/qbittorrent/qBittorrent/blob/master/Changelog (Add Search tab to WebUI)

Therefor this issue can be reopened.

Search is a valuable feature and I'd really appreciate having it available with this docker container :)

Here's a screenshot of it in action in the web UI:
![2020-04-17 05_53_53-qBittorrent v4 2 3 Web UI](https://user-images.githubusercontent.com/33176142/79530532-d7e42600-806f-11ea-88f6-cd625e4f4db3.png)

**Comment by wernight** [comment]
Newest version has the search engines.
