### ISSUE TITLE
Issue running on Debian Wheezy

### ISSUE THREAD

**Issue by fumantsu** [wernight/docker-qbittorrent#2]
I trying to run the container on Debian Wheezy and I got this on the log:
qbittorrent-nox: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory. Container (latest) is not running. Any idea?

**Comment by wernight** [comment]
Fixed. Please pull new version (in about 15 min from now):

    $ docker pull wernight/qbittorrent

**Comment by wernight** [comment]
Arg build failed. Fixing..

**Comment by fumantsu** [comment]
I didn't see any error.

**Comment by wernight** [comment]
Ok was only on tag 3.3. Should work now.
