### ISSUE TITLE
Odd Request

### ISSUE THREAD

**Issue by deldran** [wernight/docker-qbittorrent#9]
So this is not an issue, but was hoping I could get your assistance or request something new.
I have tried to fork your repo to customize the docker for myself, but I am running into issue with that as I am not a programmer, so some of these things escape me.

I use a lot of automation to manage my media library.  I have recently switched to UnRAID from windows, and there is not a docker available to suit my needs.

I use filebot to rename media files after they download, but no docker currently exists with a torrent client and filebot inside the same docker.  I know this is not ideal, as the point of dockers is to run each application in its own container, but for ease of use I would like to get filebot and qbittorrent functioning inside the same docker.

I have the ability to get this all setup in a linux machine, but getting it built from a docker file, then running properly is a bit beyond my abilities at this point.  I am trying to learn though.

I would love to work with you to create a branch or something else to get this working.  Let me know if you are interested.

Thanks.

**Comment by wernight** [comment]
This isn't a good place for such a report, but I'll try to answer it briefly anyway just this once.

First you shouldn't try to have everything in a single Docker. As appealing as a all-in-one solution may sound, you'll have a lot less flexibility and it's easy to have multiple docker containers linked. `docker-compose.yml` files are really good to set up simple links like that. For example you can have those Docker:

 - [`wernight/qbittorrent`](https://hub.docker.com/r/wernight/qbittorrent/) (this one)
 - [`couchpotato/couchpotato`](https://hub.docker.com/r/couchpotato/couchpotato/) linked to qbt to renaming and auto-retrieval.
 - [`wernight/plex-media-server`](https://hub.docker.com/r/wernight/plex-media-server/) with the same shared directory mounted, for streaming, possibly linked to CouchPotato so the later can ping it.

Network sharing is done using `--link` and file sharing is done via `-v` (mounting volumes) either hosted in a relative directory or in a data container, or such.
